"""
src/vision/stereo.py

Stereo depth and size estimation from dual Pi Camera Module 3 frames.

Phase 5: Stub implementation — interfaces defined, logic deferred to Phase 6.
Phase 6: Full implementation after cameras are physically mounted in their
         permanent positions and stereo calibration has been run.

Why stub now?
    Defining the interface in Phase 5 means Phase 6 is purely additive —
    no changes to BirdAgent, BirdObservation, or capture modules when
    stereo is activated. The Phase 6 developer fills in _rectify(),
    _compute_disparity(), and _disparity_to_depth() without touching
    any other module.

Physical requirements for Phase 6 implementation:
    1. Cameras mounted in fixed rigid positions, 8cm horizontal baseline
       (set in configs/hardware.yaml: cameras.stereo.baseline_cm).
    2. Stereo calibration run via scripts/calibrate_stereo.py:
         python scripts/calibrate_stereo.py --checkerboard 9x6 --square-mm 25
       Saves calibration matrices to models/stereo/calibration.npz.
    3. Camera positions must NOT change after calibration — any physical
       movement invalidates the calibration matrices and requires rerunning.

Stereo depth math overview (for Phase 6 implementer):
    Given two rectified frames and a detected bird bounding box (x, y, w, h):
        1. Compute disparity map via cv2.StereoSGBM on the bounding box region.
        2. Median disparity d from the bounding box region.
        3. depth_cm = (focal_length_px × baseline_cm) / d
        4. size_cm  = (bounding_box_height_px × depth_cm) / focal_length_px
    focal_length_px is extracted from the calibration matrices saved in step 2.

Dependencies (Phase 6 only — not imported in Phase 5):
    opencv-python-headless >= 4.8   — stereo rectification and SGBM disparity
    numpy                           — array operations
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np

logger = logging.getLogger(__name__)


class CalibrationRequiredError(Exception):
    """
    Raised when StereoEstimator.estimate() is called but stereo calibration
    matrices have not been loaded.

    Resolution: run scripts/calibrate_stereo.py with cameras in their
    permanent mounted positions, then retry.
    """


class StereoEstimator:
    """
    Estimates depth and physical size of a detected bird using stereo disparity.

    Phase 5: All public methods raise NotImplementedError or
    CalibrationRequiredError — the interface exists but is not yet active.

    Phase 6: Implement _rectify(), _compute_disparity(), _disparity_to_depth()
    after stereo calibration has been run. No other module changes required.

    Usage (Phase 6):
        estimator = StereoEstimator.from_config("configs/")
        estimator.load_calibration()
        depth_cm, size_cm = estimator.estimate(
            frame_primary, frame_secondary, detection_box=(x, y, w, h)
        )
    """

    def __init__(
        self,
        calibration_path: str | Path,
        baseline_cm: float,
    ) -> None:
        """
        Args:
            calibration_path: Path to stereo calibration matrices (.npz).
                              Generated by scripts/calibrate_stereo.py.
                              File does not exist until Phase 6 calibration is run.
            baseline_cm:      Center-to-center lens separation in cm.
                              Must match the physical mounting distance set at
                              install time. Set in hardware.yaml: cameras.stereo.baseline_cm.
        """
        self.calibration_path = Path(calibration_path)
        self.baseline_cm = baseline_cm
        self._calibrated = False

        # Phase 6: these will hold OpenCV calibration matrices after load_calibration()
        self._camera_matrix_left: np.ndarray | None = None
        self._camera_matrix_right: np.ndarray | None = None
        self._dist_left: np.ndarray | None = None
        self._dist_right: np.ndarray | None = None
        self._R: np.ndarray | None = None  # rotation matrix
        self._T: np.ndarray | None = None  # translation vector
        self._focal_length_px: float | None = None  # extracted at load time

        logger.info(
            "StereoEstimator initialized | baseline=%.1fcm calibration=%s",
            baseline_cm,
            calibration_path,
        )

    @classmethod
    def from_config(cls, config_dir: str | Path) -> StereoEstimator:
        """
        Construct a StereoEstimator from configs/ directory.

        Reads hardware.yaml for baseline_cm and calibration_path.
        Does not load calibration matrices — call load_calibration() explicitly.

        Args:
            config_dir: Path to the configs/ directory.

        Returns:
            Configured StereoEstimator instance (not yet calibrated).
        """
        import yaml

        config_dir = Path(config_dir)
        with (config_dir / "hardware.yaml").open() as f:
            hw = yaml.safe_load(f)

        stereo = hw["cameras"]["stereo"]
        calibration_path = stereo["calibration_path"]
        baseline_cm = float(stereo["baseline_cm"])

        return cls(calibration_path=calibration_path, baseline_cm=baseline_cm)

    def load_calibration(self) -> None:
        """
        Load stereo calibration matrices from disk.

        Phase 5: Raises CalibrationRequiredError — calibration file does not
        exist until Phase 6 calibration procedure is run.

        Phase 6 implementation:
            data = np.load(self.calibration_path)
            self._camera_matrix_left  = data["camera_matrix_left"]
            self._camera_matrix_right = data["camera_matrix_right"]
            self._dist_left           = data["dist_left"]
            self._dist_right          = data["dist_right"]
            self._R                   = data["R"]
            self._T                   = data["T"]
            self._focal_length_px     = float(self._camera_matrix_left[0, 0])
            self._calibrated          = True

        Raises:
            CalibrationRequiredError: If calibration file does not exist.
        """
        if not self.calibration_path.exists():
            raise CalibrationRequiredError(
                f"Stereo calibration file not found: {self.calibration_path}. "
                "Run scripts/calibrate_stereo.py with cameras in their permanent "
                "mounted positions before activating stereo depth estimation. "
                "This is a Phase 6 task — Phase 5 runs without stereo depth."
            )

        # Phase 6: load matrices here (see docstring above)
        raise NotImplementedError(
            "StereoEstimator.load_calibration() is not yet implemented. "
            "Implement in Phase 6 after running scripts/calibrate_stereo.py."
        )

    def estimate(
        self,
        frame_primary: np.ndarray,
        frame_secondary: np.ndarray,
        detection_box: tuple[int, int, int, int],
    ) -> tuple[float, float]:
        """
        Estimate depth and body size of a detected bird using stereo disparity.

        Args:
            frame_primary:   Full resolution (H, W, 3) uint8 RGB from primary camera.
                             Must be the raw (uncropped) frame for correct geometry.
            frame_secondary: Full resolution (H, W, 3) uint8 RGB from secondary camera.
            detection_box:   Bounding box (x, y, width, height) of detected bird
                             in primary camera frame coordinates.
                             Provided by Phase 6 object detector (YOLO via Hailo).

        Returns:
            Tuple of (depth_cm, size_cm):
                depth_cm: Estimated distance from cameras to bird in cm.
                size_cm:  Estimated bird body length in cm.

        Raises:
            CalibrationRequiredError: If load_calibration() has not been called.
            NotImplementedError:      Always in Phase 5.

        Phase 6 implementation outline:
            if not self._calibrated:
                raise CalibrationRequiredError(...)
            left_rect, right_rect = self._rectify(frame_primary, frame_secondary)
            disparity = self._compute_disparity(left_rect, right_rect, detection_box)
            depth_cm, size_cm = self._disparity_to_depth(disparity, detection_box)
            return depth_cm, size_cm
        """
        if not self._calibrated:
            raise CalibrationRequiredError(
                "StereoEstimator is not calibrated. "
                "Call load_calibration() after running scripts/calibrate_stereo.py."
            )

        raise NotImplementedError(
            "StereoEstimator.estimate() is not yet implemented. "
            "Implement _rectify(), _compute_disparity(), _disparity_to_depth() "
            "in Phase 6 after stereo calibration is complete."
        )

    def _rectify(
        self,
        frame_primary: np.ndarray,
        frame_secondary: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray]:
        """
        Apply stereo rectification to align corresponding rows in both frames.

        Phase 6: Use cv2.stereoRectify() + cv2.initUndistortRectifyMap() +
        cv2.remap() to produce rectified image pairs where corresponding
        points lie on the same horizontal scanline.

        Raises:
            NotImplementedError: Always in Phase 5.
        """
        raise NotImplementedError("Phase 6: implement stereo rectification.")

    def _compute_disparity(
        self,
        left_rect: np.ndarray,
        right_rect: np.ndarray,
        detection_box: tuple[int, int, int, int],
    ) -> float:
        """
        Compute median disparity within the bird bounding box region.

        Phase 6: Use cv2.StereoSGBM on the ROI defined by detection_box.
        Return median disparity value in pixels.

        Raises:
            NotImplementedError: Always in Phase 5.
        """
        raise NotImplementedError("Phase 6: implement disparity computation.")

    def _disparity_to_depth(
        self,
        disparity_px: float,
        detection_box: tuple[int, int, int, int],
    ) -> tuple[float, float]:
        """
        Convert disparity to metric depth and bird body size.

        Phase 6 formulas:
            depth_cm = (focal_length_px × baseline_cm) / disparity_px
            size_cm  = (detection_box[3] × depth_cm) / focal_length_px
            where detection_box[3] is the bounding box height in pixels.

        Raises:
            NotImplementedError: Always in Phase 5.
        """
        raise NotImplementedError("Phase 6: implement disparity-to-depth conversion.")
