"""
src/audio/classify.py

Wraps a fine-tuned audio model to produce a ClassificationResult.

Architecture:
    - Fine-tuned model: lightweight CNN trained on mel spectrograms of our
      18 SD species (output of src.audio.preprocess).
    - Pretrained baseline: birdnetlib wraps BirdNET-Analyzer for comparison.
    - At inference, AudioClassifier.predict() runs the fine-tuned model.
    - The fine-tuned model is trained in notebooks/audio_birdnet.ipynb and
      saved to models/audio/finetuned_sdbirds.pt.

Input:  mel spectrogram — float32 array of shape (n_mels, time_frames),
        as returned by src.audio.preprocess.AudioPreprocessor.process_file().
Output: ClassificationResult (src.data.schema)

Design notes:
    - Model is loaded lazily on first predict() call to keep __init__ fast.
    - CHW transpose is applied here, not in preprocess — preprocess outputs
      (n_mels, time_frames), model expects (1, n_mels, time_frames).
    - species_list_path resolves to configs/species.yaml — the same file used
      by splitter.py, so label ordering is always consistent.
    - label_map.json (models/label_map.json) maps int index → species_code.
      It is generated by scripts/generate_label_map.py during training setup.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import yaml

from src.data.schema import ClassificationResult, Modality

logger = logging.getLogger(__name__)


class AudioClassifier:
    """
    Wrapper around our fine-tuned audio CNN for SD bird species classification.

    The model is a lightweight CNN (see notebooks/audio_birdnet.ipynb) trained
    on mel spectrograms extracted from Xeno-canto SD recordings.

    Usage:
        classifier = AudioClassifier.from_config("configs/paths.yaml")
        spectrogram = AudioPreprocessor().process_file("clip.wav")
        result = classifier.predict(spectrogram)
    """

    MODEL_VERSION = "audio-cnn-sdbirds-v1"

    def __init__(
        self,
        model_path: str,
        label_map_path: str,
        species_list_path: str,
        device: str | None = None,
    ) -> None:
        """
        Args:
            model_path: Path to fine-tuned model weights (.pt checkpoint).
                        Saved by notebooks/audio_birdnet.ipynb.
            label_map_path: Path to label_map.json (int index → species_code).
            species_list_path: Path to configs/species.yaml (code → names).
            device: Torch device string ('cpu', 'cuda'). Auto-detected if None.
        """
        self.model_path = Path(model_path)
        self.label_map_path = Path(label_map_path)
        self.species_list_path = Path(species_list_path)
        self.device = torch.device(
            device if device else ("cuda" if torch.cuda.is_available() else "cpu")
        )
        self._model: nn.Module | None = None
        self._label_map: dict[int, str] = {}  # int index → species_code
        self._species_meta: dict[str, dict] = {}  # code → {common_name, scientific_name}

        logger.info(
            "AudioClassifier initialized | model=%s device=%s",
            self.model_path,
            self.device,
        )

    @classmethod
    def from_config(cls, config_path: str) -> AudioClassifier:
        """
        Construct an AudioClassifier from configs/paths.yaml.

        Args:
            config_path: Path to configs/paths.yaml.

        Returns:
            Configured AudioClassifier instance (model not yet loaded).
        """
        config_path = Path(config_path)
        with config_path.open() as f:
            cfg = yaml.safe_load(f)

        model_path = cfg["models"]["audio_finetuned"]
        label_map_path = cfg["models"]["label_map"]
        # Resolve species.yaml relative to configs/ directory
        species_list_path = config_path.parent / "species.yaml"

        logger.info("AudioClassifier.from_config | paths.yaml=%s", config_path)
        return cls(
            model_path=model_path,
            label_map_path=label_map_path,
            species_list_path=str(species_list_path),
        )

    def _load(self) -> None:
        """
        Lazily load model weights, label map, and species metadata.

        Called automatically on first predict(). Separated from __init__ so
        that constructing a classifier (e.g. in tests) does not require weights
        to exist on disk.
        """
        # Load species metadata from species.yaml
        with self.species_list_path.open() as f:
            species_cfg = yaml.safe_load(f)
        self._species_meta = {
            s["code"]: {
                "common_name": s["common_name"],
                "scientific_name": s["scientific_name"],
            }
            for s in species_cfg["species"]
        }

        # Load label map: {"0": "HOFI", "1": "MODO", ...}
        with self.label_map_path.open() as f:
            raw = json.load(f)
        self._label_map = {int(k): v for k, v in raw.items()}

        # Load model
        n_classes = len(self._label_map)
        self._model = _build_audio_cnn(n_classes=n_classes)
        checkpoint = torch.load(self.model_path, map_location=self.device)
        self._model.load_state_dict(checkpoint["model_state_dict"])
        self._model.to(self.device)
        self._model.eval()

        logger.info(
            "AudioClassifier loaded | classes=%d device=%s weights=%s",
            n_classes,
            self.device,
            self.model_path,
        )

    def predict(self, spectrogram: np.ndarray) -> ClassificationResult:
        """
        Run inference on a mel spectrogram and return the top species prediction.

        Args:
            spectrogram: Float32 array of shape (n_mels, time_frames), dB-scaled,
                         as returned by AudioPreprocessor.process_file().

        Returns:
            ClassificationResult for the highest-confidence species prediction.

        Raises:
            ValueError: If spectrogram has unexpected shape or dtype.
            RuntimeError: If model weights have not been trained yet.
        """
        if not self.model_path.exists():
            raise RuntimeError(
                f"Model weights not found at {self.model_path}. "
                "Run notebooks/audio_birdnet.ipynb to train the model first."
            )

        if self._model is None:
            self._load()

        if spectrogram.ndim != 2:
            raise ValueError(
                f"Expected 2-D spectrogram (n_mels, time_frames), " f"got shape {spectrogram.shape}"
            )

        # (n_mels, time_frames) → (1, 1, n_mels, time_frames): batch + channel
        tensor = (
            torch.from_numpy(spectrogram.astype(np.float32))
            .unsqueeze(0)  # channel dim
            .unsqueeze(0)  # batch dim
            .to(self.device)
        )

        with torch.no_grad():
            logits = self._model(tensor)  # (1, n_classes)
            probs = torch.softmax(logits, dim=1)  # (1, n_classes)
            confidence, idx = probs.max(dim=1)

        species_code = self._label_map[idx.item()]
        meta = self._species_meta.get(species_code, {})

        return ClassificationResult(
            species_code=species_code,
            common_name=meta.get("common_name", species_code),
            scientific_name=meta.get("scientific_name", ""),
            confidence=float(confidence.item()),
            modality=Modality.AUDIO,
            model_version=self.MODEL_VERSION,
        )


def _build_audio_cnn(n_classes: int) -> nn.Module:
    """
    Build the lightweight CNN used for mel spectrogram classification.

    Architecture: two conv blocks + global average pooling + linear head.
    Designed to accept (1, n_mels, time_frames) input — the channel dimension
    is added by predict() before passing to the model.

    This function is the single source of truth for the model architecture.
    It is called both here (inference) and in the training notebook (training),
    so the architecture is always in sync between training and inference.

    Args:
        n_classes: Number of output classes (species). Must match label_map.

    Returns:
        Untrained nn.Module. Caller loads weights via load_state_dict().
    """
    return nn.Sequential(
        # Block 1: (1, n_mels, T) → (32, n_mels/2, T/2)
        nn.Conv2d(1, 32, kernel_size=3, padding=1),
        nn.BatchNorm2d(32),
        nn.ReLU(),
        nn.MaxPool2d(2),
        # Block 2: (32, n_mels/2, T/2) → (64, n_mels/4, T/4)
        nn.Conv2d(32, 64, kernel_size=3, padding=1),
        nn.BatchNorm2d(64),
        nn.ReLU(),
        nn.MaxPool2d(2),
        # Block 3: (64, n_mels/4, T/4) → (128, n_mels/8, T/8)
        nn.Conv2d(64, 128, kernel_size=3, padding=1),
        nn.BatchNorm2d(128),
        nn.ReLU(),
        nn.MaxPool2d(2),
        # Global average pool → (128,)
        nn.AdaptiveAvgPool2d(1),
        nn.Flatten(),
        nn.Dropout(0.3),
        nn.Linear(128, n_classes),
        # No softmax here — CrossEntropyLoss expects raw logits during training.
        # Softmax applied in predict() at inference time.
    )
